# Generated by Django 3.0.2 on 2020-07-19 18:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('my_custom_form', '0002_auto_20200719_1725'),
    ]

    operations = [
        migrations.DeleteModel(
            name='User',
        ),
    ]
